name: Deploy to Surge

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Surge
        run: npm install --global surge

      - name: Hacer deploy a Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          cd Source/html
          surge . delizioso-pizza.surge.sh --token $SURGE_TOKEN
